const listApi = {
  count: 1421,
  entries: [
    {
      API: 'AdoptAPet',
      Description: 'Resource to help get pets adopted',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.adoptapet.com/public/apis/pet_list.html',
      Category: 'Animals',
    },
    {
      API: 'Axolotl',
      Description: 'Collection of axolotl pictures and facts',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://theaxolotlapi.netlify.app/',
      Category: 'Animals',
    },
    {
      API: 'Cat Facts',
      Description: 'Daily cat facts',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://alexwohlbruck.github.io/cat-facts/',
      Category: 'Animals',
    },
    {
      API: 'Cataas',
      Description: 'Cat as a service (cats pictures and gifs)',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://cataas.com/',
      Category: 'Animals',
    },
    {
      API: 'Cats',
      Description: 'Pictures of cats from Tumblr',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://docs.thecatapi.com/',
      Category: 'Animals',
    },
    {
      API: 'Dog Facts',
      Description: 'Random dog facts',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://dukengn.github.io/Dog-facts-API/',
      Category: 'Animals',
    },
    {
      API: 'Dog Facts',
      Description: 'Random facts of Dogs',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://kinduff.github.io/dog-api/',
      Category: 'Animals',
    },
    {
      API: 'Dogs',
      Description: 'Based on the Stanford Dogs Dataset',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://dog.ceo/dog-api/',
      Category: 'Animals',
    },
    {
      API: 'eBird',
      Description:
        'Retrieve recent or notable birding observations within a region',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://documenter.getpostman.com/view/664302/S1ENwy59',
      Category: 'Animals',
    },
    {
      API: 'FishWatch',
      Description: 'Information and pictures about individual fish species',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.fishwatch.gov/developers',
      Category: 'Animals',
    },
    {
      API: 'HTTP Cat',
      Description: 'Cat for every HTTP Status',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://http.cat/',
      Category: 'Animals',
    },
    {
      API: 'HTTP Dog',
      Description: 'Dogs for every HTTP response status code',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://http.dog/',
      Category: 'Animals',
    },
    {
      API: 'IUCN',
      Description: 'IUCN Red List of Threatened Species',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'no',
      Link: 'http://apiv3.iucnredlist.org/api/v3/docs',
      Category: 'Animals',
    },
    {
      API: 'MeowFacts',
      Description: 'Get random cat facts',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://github.com/wh-iterabb-it/meowfacts',
      Category: 'Animals',
    },
    {
      API: 'Movebank',
      Description: 'Movement and Migration data of animals',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://github.com/movebank/movebank-api-doc',
      Category: 'Animals',
    },
    {
      API: 'Petfinder',
      Description:
        'Petfinder is dedicated to helping pets find homes, another resource to get pets adopted',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.petfinder.com/developers/',
      Category: 'Animals',
    },
    {
      API: 'PlaceBear',
      Description: 'Placeholder bear pictures',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://placebear.com/',
      Category: 'Animals',
    },
    {
      API: 'PlaceDog',
      Description: 'Placeholder Dog pictures',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://place.dog',
      Category: 'Animals',
    },
    {
      API: 'PlaceKitten',
      Description: 'Placeholder Kitten pictures',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://placekitten.com/',
      Category: 'Animals',
    },
    {
      API: 'RandomDog',
      Description: 'Random pictures of dogs',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://random.dog/woof.json',
      Category: 'Animals',
    },
    {
      API: 'RandomDuck',
      Description: 'Random pictures of ducks',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://random-d.uk/api',
      Category: 'Animals',
    },
    {
      API: 'RandomFox',
      Description: 'Random pictures of foxes',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://randomfox.ca/floof/',
      Category: 'Animals',
    },
    {
      API: 'RescueGroups',
      Description: 'Adoption',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://userguide.rescuegroups.org/display/APIDG/API+Developers+Guide+Home',
      Category: 'Animals',
    },
    {
      API: 'Shibe.Online',
      Description: 'Random pictures of Shiba Inu, cats or birds',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'http://shibe.online/',
      Category: 'Animals',
    },
    {
      API: 'The Dog',
      Description:
        'A public service all about Dogs, free to use when making your fancy new App, Website or Service',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://thedogapi.com/',
      Category: 'Animals',
    },
    {
      API: 'xeno-canto',
      Description: 'Bird recordings',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://xeno-canto.org/explore/api',
      Category: 'Animals',
    },
    {
      API: 'Zoo Animals',
      Description: 'Facts and pictures of zoo animals',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://zoo-animal-api.herokuapp.com/',
      Category: 'Animals',
    },
    {
      API: 'AniAPI',
      Description: 'Anime discovery, streaming & syncing with trackers',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://aniapi.com/docs/',
      Category: 'Anime',
    },
    {
      API: 'AniDB',
      Description: 'Anime Database',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'https://wiki.anidb.net/HTTP_API_Definition',
      Category: 'Anime',
    },
    {
      API: 'AniList',
      Description: 'Anime discovery & tracking',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/AniList/ApiV2-GraphQL-Docs',
      Category: 'Anime',
    },
    {
      API: 'AnimeChan',
      Description: 'Anime quotes (over 10k+)',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://github.com/RocktimSaikia/anime-chan',
      Category: 'Anime',
    },
    {
      API: 'AnimeFacts',
      Description: 'Anime Facts (over 100+)',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://chandan-02.github.io/anime-facts-rest-api/',
      Category: 'Anime',
    },
    {
      API: 'AnimeNewsNetwork',
      Description: 'Anime industry news',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.animenewsnetwork.com/encyclopedia/api.php',
      Category: 'Anime',
    },
    {
      API: 'Catboy',
      Description: 'Neko images, funny GIFs & more',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://catboys.com/api',
      Category: 'Anime',
    },
    {
      API: 'Danbooru Anime',
      Description: 'Thousands of anime artist database to find good anime art',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://danbooru.donmai.us/wiki_pages/help:api',
      Category: 'Anime',
    },
    {
      API: 'Jikan',
      Description: 'Unofficial MyAnimeList API',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://jikan.moe',
      Category: 'Anime',
    },
    {
      API: 'Kitsu',
      Description: 'Anime discovery platform',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://kitsu.docs.apiary.io/',
      Category: 'Anime',
    },
    {
      API: 'MangaDex',
      Description: 'Manga Database and Community',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.mangadex.org/docs.html',
      Category: 'Anime',
    },
    {
      API: 'Mangapi',
      Description: 'Translate manga pages from one language to another',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://rapidapi.com/pierre.carcellermeunier/api/mangapi3/',
      Category: 'Anime',
    },
    {
      API: 'MyAnimeList',
      Description: 'Anime and Manga Database and Community',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://myanimelist.net/clubs.php?cid=13727',
      Category: 'Anime',
    },
    {
      API: 'NekosBest',
      Description: 'Neko Images & Anime roleplaying GIFs',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://docs.nekos.best',
      Category: 'Anime',
    },
    {
      API: 'Shikimori',
      Description: 'Anime discovery, tracking, forum, rates',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://shikimori.one/api/doc',
      Category: 'Anime',
    },
    {
      API: 'Studio Ghibli',
      Description: 'Resources from Studio Ghibli films',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://ghibliapi.herokuapp.com',
      Category: 'Anime',
    },
    {
      API: 'Trace Moe',
      Description:
        'A useful tool to get the exact scene of an anime from a screenshot',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://soruly.github.io/trace.moe-api/#/',
      Category: 'Anime',
    },
    {
      API: 'Waifu.im',
      Description:
        'Get waifu pictures from an archive of over 4000 images and multiple tags',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://waifu.im/docs',
      Category: 'Anime',
    },
    {
      API: 'Waifu.pics',
      Description: 'Image sharing platform for anime images',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://waifu.pics/docs',
      Category: 'Anime',
    },
  ],
};

export default listApi;
